library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)
library(tidyr)
library(data.table)
library(gridExtra)
library(lmtest)
library(MuMIn)
library(MASS)

mydata = read.csv("measurements.csv")
limb_vol = c(((Limb_width/2)^2)*Limb_length*3.14)
mydata2 = cbind(mydata, limb_vol)
head(mydata2)
write.csv(mydata2, "newmeasurements.csv")
